export const DATE_FORMAT = {
  FULL_MONTH_YEAR: 'MMMM, YYYY',
  DAY_MONTH_YEAR: 'DD.MM.YY',
  SHORT_DAY: 'D',
  HOUR_MINUTES: 'LT',
  SHORT_MONTH_DAY_YEAR: 'll',
  SHORT_MONTH_DAY_HOURS_MINUTES: 'MMM D, LT',
};
